apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakV4TWpNeApNek00TkRsYUZ3MDBNakV4TWpNeE16TTRORGxhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDYktJQWpSSTJHTlY1MmJTOFlSR2R4dy9QZHlGc09VWDdsMTAvUzlLT3FZZElIYlZwdApDQUE2U3pvcGxhNkc1VXlEMEd6V21QSWxxNWxTQllmTThBcnE1ZG5GV0xleXF6MTVxRGtjdlRzTTVQZFU1YW9DCnl3S29vOExmNTVJODFzcnhRTkd1WFlFelBTeklnaDI1U3dyZy81ek5rSEdBaHhJaCs1RzFKOHBZUW5vRm5jWnEKUFExYnhBZ2RNeFk3RDhDMFFzVW9MSWFIWFRZVFkzL0U5SVVwditrbE42ZGFaUjJacmVtV25ZV3MzWTVSelpvNwpmVDhzSlhwd1dURkxJK1pkT2d5NjN3ZGJ0Tk0yQVd6ZE0ydllESThBWUd1MFFLU3QrVS9HcXJ2TEtFaWpDSjNYCnMzRjg3cjk2ZGYrVjVNaXN3NWN6YlRqdk9heEg0YU9SRXZnVEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJIanFBaWg5b05XK2FLZnFHegp6MGZXVmsrWlhEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFrOWhsNFBpWS9xMTZoM2NEK0RnbmVVdWdhMVpxClpFY3o5ZC9yWUJ2QmhzSEdZSE1NL085QnMvK0hjcDJ1VkQ2MGJXTXNxZXU5TmFSSitncjVrRkR0dXN2dFpXMlIKS3dLV2xPOUt4UGs4OUZuQ3ZZa0VFVmlMblVNZGQ5K0NwcnZoNUV0eUhYWmpKQm8zazhIYWRmTDM0ejhBM2h6QgpCT1dqOHovZDhXeTZqZ1JvQXRhc251amhsWmtVV2IwWEFKVXlPdmdudkptdElwSitXaTdFSDJEQVJJNWduMXk5CnZ5OUsyRUhwdksrWmFJTkhGOVdGRGUvZTFWMHd1Yld2MzJMc3hOblExMFBnZEtYMkljaWZXU3NXNW5RVjFjSlEKcFhnTzJSWlBjTGg0dER2NnpENXQ4eGFEL0tBZTdNb1VpLytwV2YzOFVwS0w0N3NXSlJVblFmRXNCQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://953b7b46-36bf-43f4-be4b-38fad59c8bb7.k8s.ondigitalocean.com
  name: do-blr1-k8s-1-24-4-do-0-blr1-1669209567149
contexts:
- context:
    cluster: do-blr1-k8s-1-24-4-do-0-blr1-1669209567149
    user: do-blr1-k8s-1-24-4-do-0-blr1-1669209567149-admin
  name: do-blr1-k8s-1-24-4-do-0-blr1-1669209567149
current-context: do-blr1-k8s-1-24-4-do-0-blr1-1669209567149
kind: Config
preferences: {}
users:
- name: do-blr1-k8s-1-24-4-do-0-blr1-1669209567149-admin
  user:
    token: dop_v1_ab142e110168c0608acc603befbc08ef84a546e4df6dd528a401e4c5aef9460e
